### ISSUE TITLE
Data error when saving vehicle tab info

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#100]
Check the json that is being PUT.  It seems that at least sometimes it is mixing up the phone number fields.

**Comment by DanielCaspers** [comment]
@scaspers please give work orders I can verify against if you'd like further help. I've looked but haven't found anything that looks like a smoking gun on my side yet unless you'd like me to step through the debugger on a given work order.

**Comment by scaspers** [comment]
Looks like the error was in the D3-API input parser.  When an array object contained NULLS in certain fields those fields would shift at the PHP level and the data returned to PICK would be out of order.   Logic was inserted to make NULL = "null" (string) and then PICK would convert that into an empty string before saving.
