### ISSUE TITLE
Customer waiting flag

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#102]
Wondering if there is some way to 'flag' a work order with color or blink on the orders table and maybe in the customer and vehicle tabs?
There is a new value in the orders json object `"customerWaiting": 1524002040` which is a timestamp.  The value is null if the customer is NOT waiting.

**Comment by DanielCaspers** [comment]
[Implementation notes](https://datatables.net/forums/discussion/38212/table-row-conditional-styling)

**Comment by scaspers** [comment]
This is where I was wondering if you could insert into the datatables init:
*** Datatables init javascript
`		"createdRow": function( row, data, dataIndex ) {
			if ( data.customerWaiting > 0 ) {
			  $('td', row).eq(1).addClass( 'waitFlag' );
			}
			if ( data.orderStatus.statusCode === 22 ) {
			  $('td', row).eq(3).addClass( 'InspCompleteFlag' );
			}
		}
`
***CSS
`.waitFlag {
	background: yellow !important;
    color:#000 !important;
	font-weight: bold !important;
}

.InspCompleteFlag {
	background: red !important;
    color:#FFF !important;
	font-weight: bold !important;
}
`

[example look](https://d3-devel.murphyauto.net/wostatus.php?c=004) on the In Progress tab

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy 
Here are some options for how I'd like to do the new status columns.
1. ![image](https://user-images.githubusercontent.com/6056563/39279921-9f877a10-48c1-11e8-831e-87184d9e4207.png)

2. ![image](https://user-images.githubusercontent.com/6056563/39279956-dfb20010-48c1-11e8-9ef4-0c530208d038.png)

I already have the code for both, but plan on pushing option 2. Let me know what is preferred, or if others have better ideas.

**Comment by DanielCaspers** [comment]
@scaspers with how I've implemented, I expect any changes you want will be small enough you can attempt. Please familiarize yourself with the commit to get a feel for how you'd change anything that might be requested.

**Comment by DanielCaspers** [comment]
Option 3.
![image](https://user-images.githubusercontent.com/6056563/39284264-08d0f03a-48d8-11e8-834e-50845f2f3d48.png)

**Comment by scaspers** [comment]
What do you think of thses icons?

WAITING: 
<i class="material-icons.md-36" style="color:dodgerblue;" title="Customer Waiting">assignment_ind</i>
Insp Complete:
<i class="material-icons.md-36" style="color:red;" title="Action Required">notifications_active</i>

For the work orders table we can use the standard size (24)?
I am thinking the same icons in CA-portal (Service Advisors view)[ CA-Portal #4](https://github.com/scaspers/CA-Portal/issues/4)
