### ISSUE TITLE
Change Default View in "Work Order Detail"

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#107]
Currently it is Customer. It should be Vehicle.

@scaspers @YoMurphy , do you want the tabs also re-ordered to reflect the change in default, or do you have no preference. Perhaps ask around, but typically the default tab is always leftmost when laid out horizontally like that.

**Comment by scaspers** [comment]
I would say that the tabs would NOT need to be re-ordered.
