### ISSUE TITLE
Delete inspection images when deleting an inspection

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#111]
Now that we have a way to delete images maybe we could delete the whole image directory for that order when we delete an inspection.
Just a matter of house cleaning. 
I might try this one.

**Comment by DanielCaspers** [comment]
You'll wanna look around in `ImageService.cs` and `InspectionService.cs`. The "Delete Inspection" action is defined in `InspectionsController.cs`.

I'll let you try to swim on this one and give you pointers along the way and see how you do flying solo ;)

A good time to ask for any live help would be this Friday night while I'm driving.

**Comment by DanielCaspers** [comment]
@scaspers, how would you feel if we delete the images, but leave the empty folders? It seems to me that its not hurting anything leaving the folder around.

**Comment by DanielCaspers** [comment]
![jun 30 2018 9_53 pm](https://user-images.githubusercontent.com/6056563/42130640-5973e2c0-7cb0-11e8-8ae9-0859e85acc46.gif)
Here is the new behavior of delete. Let me know if you want me to spend time cleaning up empty directories also, or if your concern was mostly on disk space.

**Comment by DanielCaspers** [comment]
@scaspers, at the end of this weekend when there is a build to test, please test this functionality out on a Mono server and let me know if its working alright. I've set it to delete folders, but we may run into challenges there.

**Comment by scaspers** [comment]
All is well
