### ISSUE TITLE
Mark an inspection item as addressing customer concern

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#114]
When a customer drops off a vehicle they usually ask for specific concerns to be looked at.  When we do the inspection we would like a way to mark\check an inspection item as something that is related to what they brought the vehicle in for.

This has a related issue on CAPortal [#7](https://github.com/scaspers/CA-Portal/issues/7)

**Comment by DanielCaspers** [comment]
@scaspers , please leave feedback for further development after testing tomorrow, or unassign and close.
