### ISSUE TITLE
order notes failed to save

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#121]
Pat A. reported.
Two times, (once I witnessed) he entered order notes from an inspection, made an edit and when he pressed save nothing happened (no errors, nothing).  We could click outside of the modal and it would disappear.  
We could go back into order notes and the changes would not be there and we would again attempt to change with no joy.
I then refreshed the inspection page and we opened order notes again to make edits and Success!

This may be the same problem that Micah was trying to tell me about which was also very intermittent.

**Comment by YoMurphy** [comment]
This was also experienced by Brad Czubernat that I verified just this morning. I did not refresh the browser but I backed out of the wo and went back into the order before it worked.

**Comment by DanielCaspers** [comment]
Think it's related to order locking also? Like #120?

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy I'm nearly certain this is fixed. If it'd be helpful, I can take a GIF recording of what the issue I solved looked like before and how it looks now. Let me know. Otherwise, read steps to reproduce the issue in #120 comments.
