### ISSUE TITLE
Link to past inspections

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#128]
John was asking if it would be possible to see a list of the digital inspections that have been performed in a chronological order and be able to look at the last inspection results.

I thought that maybe we could add link in the history model if an inspection was present.  The link would be to the SA version of the report in a new browser tab.  I could pass the inspectionID guid with the orders endpoint to save DI the lookup?

**Comment by DanielCaspers** [comment]
Seems reasonable. We may want this functionality from PIC anyways for the CA portal. 

I'd store just the Guid, or both the Guid and the link, but don't just store the link.

I think it'd be better for DI to build the link, but I could be persuaded otherwise.

**Comment by DanielCaspers** [comment]
@scaspers , please file a new issue in more detail based on user feedback. I'm considering the original spirit of this ticket as complete.
