### ISSUE TITLE
Unable to add new inspection checklist

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#130]
When trying to add new checklist it forces me to add a picture even though we don't use them and then it gives this error when clicking ADD:
![image](https://user-images.githubusercontent.com/12421599/44789726-f7f56780-ab62-11e8-9e80-679120c54261.png)

**Comment by DanielCaspers** [comment]
@scaspers I've fixed this, but it requires you to change DB. See commit for details. I tested for impacts to InspectionImages, but I can see them just fine and toggle their visibility without issues.
