### ISSUE TITLE
Notes are lost on tab if WO is locked by another.

### ISSUE THREAD

**Issue by YoMurphy** [DanielCaspers/DigitalInspection#132]
When a tech is in a WO on the tablet they can select the notes icon to add notes. After all the notes are entered they hit Save and if the WO is locked by another user or Service Advisor the tablet displays the Lock warning but then clears any notes taken.  Big irritant to the tech depending on how many notes were written. 
Suggestion 1: Can the notes be saved and cued to post when lock is released?
Suggestion 2: Can the Lock warning post when the Notes icon is first selected and/or the tablet could then lock the order while editing notes.
Suggestion 3: ???

**Comment by DanielCaspers** [comment]
Yeah, this was a hard design decision when we made it. 

We decided when we did this to lock only when the tech confirmed their notes, not on opening.

I believe the **quickest fix is suggestion 2**, but we've discussed queueing at length also. @scaspers , lmk on prioritization of this and if you'd rather take suggestion 2 for time's sake. If you weren't planning on having me do queueing this winter, I'd say lets take the faster road and address queueing later.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy, its now pushed, and I've added a note thats hopefully self-explanatory to users in case you don't get around to telling them. I've also published this tutorial GIF for everyone's convenience. 

![workordernotes-clipboarddemo](https://user-images.githubusercontent.com/6056563/47611136-2beaed00-da2d-11e8-89d2-6670cd481984.gif)
