### ISSUE TITLE
Add new field to CannedResponses table

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#151]
New feature to aid the implementation of DI in the Express Lube.

This will be used for special text that will be retrieved by API call and imported into the vehicle recommended services in PICK and then appear on customers invoice.

"RStext" - longtext, allow nulls, no key, default value null

**Comment by DanielCaspers** [comment]
This will require getting me authentication back into a development server to test, and we'll likely need to edit the development server SQL table to capture this new field since the app is not auto-applying DB migrations right now (at least locally for me).  Build will be on Azure.

**Comment by scaspers** [comment]
This new feature seems to work as expected.
