### ISSUE TITLE
Service Writer And Location Manager Integration

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#16]
Service advisors and location managers should have distinct roles in DI, and have different things available on the Work Orders Table view.

A LocationManager can see work orders at an elevated level across the company, but does not have access to configure anything in the checklists feature

A ServiceAdvisor sees work that they are assigned to, or for technicians they are assigned to be working with. This will be handled by a new endpoint in D3-API

- [x] Create 2 new roles, LocationManager and ServiceAdvisor. Rename User role to Tech
- [x] Add authorization attributes corresponding to permitted use on all endpoints. 
- [x] Review logic for limiting the "Checklists" menu items to disallow it in appropriate roles
- [x] Fetch table data appropriate to roles
- [x] Adjust D3-API to DI role mapping in user claims

**Comment by DanielCaspers** [comment]
@scaspers please notify here when endpoint is available.

**Comment by scaspers** [comment]
endpoint is live on v2
Works just like the tech endpoint but is "writer/####"
ie. https://d3-devel.murphyauto.net/api/v2/004/orders/writer/4024
valid writers for company#004 are 4024, 4095, 4073, 4029

**Comment by scaspers** [comment]
There are now the following roles setup with users to test:
Admin (0099003, 0099004)
Mgr(0044024, 0044095)
SvcAdvisor (0044073, 0044029)
Tech (0044019, 0044067, 0044007, 0044009)
User (0044060)

**Comment by DanielCaspers** [comment]
User is a front counter staff? Seems like we should deprecate that role IMO

**Comment by DanielCaspers** [comment]
Available on DI2 effective immediately.
