### ISSUE TITLE
Investigate Mod_Mono and App Stability

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#18]
The application seems to get tons of HTTP 500 ISEs and also seems to have to dynamically recompile on client request every time one of these is hit. 

- [ ] Attempt pre-compilation using A/B testing
- [ ] See if mod_mono should use auto configuration. 
- [ ] Stress test for ISEs with current app version. 
- [ ] Search Google and SO to determine if this is a common problem, and look for remedies.

**Comment by scaspers** [comment]
Went through the mod_mono configuration within the apache virtual server config and used the online configuration tool to help.  System now seems stable with multiple installations.  Tested "stable", "nightly-a" and "weekly" and moving between now seems as expected.
