### ISSUE TITLE
Inspection Item Image Upload

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#25]
**Problem**
After a lot of searching and trouble, I've discovered AJAX image upload is not supported by default in Vanilla ASP.NET MVC 5. I currently have Basic HTML Image Uploading working, but we may have to spend more time to get a custom AJAX image upload implementation to work, especially when it comes to the inspection portion. 

**Next Steps**
Evaluate if current HTML file uploading is sufficient for Alpha? 

If not, we should consider the following.
1. What should the user experience be like? What do we expect to see on picking a file, waiting for upload to complete, navigating away while submission is in progress, etc. 
2. Evaluate options from resources.
3. Pick and implement

**Resources**
1. [10 Possible JQuery AJAX file uploading plugins](https://www.sitepoint.com/10-jquery-ajax-file-uploader-plugins/)
2. [HTML5 File API, MDN](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications)
3. [SO Recommends - BlueIMP](http://stackoverflow.com/a/17037987/2831961)
4. [SO Recommends - JQuery Forms](http://stackoverflow.com/questions/19042116/ajax-beginform-in-mvc-to-upload-files)

**Comment by DanielCaspers** [comment]
@scaspers , does this explain our issues with duplicate images on the server?

https://stackoverflow.com/a/275791/2831961

I am using "~/Uploads" the base folder.

**Comment by DanielCaspers** [comment]
@YoMurphy @scaspers , we can now upload images to the server for inspections at full quality. After clicking "Upload", the page will wait to upload the folder, and then will refresh before a tech can continue. We can revisit this limitation later easily, but just want to keep things moving. 

However, you can't view the uploaded images using the dialog yet until I do the last large chunk of database work.

**Comment by DanielCaspers** [comment]
@scaspers, if the user experience flow is sufficiently performant for V1, I'd like to close this for now to show work to this point is satisfactory.

**Comment by scaspers** [comment]
I think we should be ok with this for now.
