### ISSUE TITLE
Tie checklists to REAL checklistItems

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#33]
Until now, I had fake checklist Items in the Checklists edit view.

We are ready to use real checklist items created from the other screens, which should bring us to nearly complete configuration of digital inspections.

**Comment by DanielCaspers** [comment]
Starting work on this! :)

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , how would you feel about me starting on integration with real work orders and inspections and saving the ChecklistItem Policy (Requires Photo & Required to Complete Inspection columns) for when we are further along? 

I think it would be wise to wait to design that bit until we see what other kinds of validation might be necessary when the technicians get a chance to use it.

**Comment by scaspers** [comment]
Sounds reasonable.  Real work orders.
