### ISSUE TITLE
Work Order Master Table

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#35]
Table should contain the following columns

1. Employee number
2. Work Order # (Can combine status if space is required)
3. Customer
4. Vehicle (Combine license for space savings, wrap to 2 lines)
5. Status (Optional based on column 2)
6. Date (Wrap to 2 lines)

For funsies, add colour of vehicle to LHS of row. 

Evaluate and integrate the [DataTables plugin ](https://datatables.net/examples/styling/material.html) for usage.

**Comment by DanielCaspers** [comment]
Up next for this is integrating with real data!

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy , Do you find it helpful to separate the color indication with a border as I've done below?I can take it or leave it, but thought it might be appreciated/useful.

I was trying to make vehicles with color WHITE or an unrecognized color (for example, someone wrote down "WHITEORANGEGREEN") be more noticeable.

![image](https://cloud.githubusercontent.com/assets/6056563/26614171/6275857c-4584-11e7-8598-2f0eee2bc0d2.png)

**Comment by YoMurphy** [comment]
I like the border.

*/Rick Murphy/*
*Murphy Automotive, Inc.*
p: 	952-997-3310 m: 952-484-5302
w: 	www.murphyauto.com <http://www.murphyauto.com> e: 
rick.murphy@murphyauto.net <mailto:rick.murphy@murphyauto.net>

dba.
ProTech Automotive
Edina Tire & Auto
Grandview Tire & Auto - Vernon
Grandview Tire & Auto - Cahill

**Comment by DanielCaspers** [comment]
Filter panels and tabbing by work order date have been deferred until more user feedback is gathered.

**Comment by DanielCaspers** [comment]
By @scaspers request, an X is now placed in the color indicator field of Vehicles which have a color field of null, or a string consisting of only whitespace.

Now, if a vehicle has a color which is not recognized, my hands are tied. So, if someone put "WHITEORANGEGREEN", it will be white without the X. As time passes, those rare examples (probably on work trucks with decals mostly) can be cleaned up by hand

![image](https://cloud.githubusercontent.com/assets/6056563/26766693/43e9009e-495c-11e7-8dea-817f09bba8e2.png)

**Comment by DanielCaspers** [comment]
If the problem with the work order falsely reporting white becomes a big enough issue, I could always manually check if the string matches one of the 140 some CSS colors.... 

https://www.w3schools.com/cssref/css_colors.asp
