### ISSUE TITLE
Work Order - Vehicle Tab

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#38]
Implement page https://drive.google.com/drive/u/0/folders/0B9irLMSVERqNRzFKOE53TXZtQ0U

1. ~~Displaying data in that form without requesting a work order lock~~
2. ~~Edit functionality, requesting the lock~~
3. ~~Saving data and releasing the lock~~
4. ~~Navigating away and releasing the lock~~ Moved to #50 
5. ~~comments text field for vehicle specific info (BE and FE when ready) - Awaiting https://github.com/scaspers/D3-API/issues/6~~
6. ~~Work description field as view only within the form~~
7. ~~Recommended Services Dialog~~

**Comment by DanielCaspers** [comment]
Note: Bug currently exists in table if trying to click entry beyond initial page size. Due to plugin, click event binder must be redone on each pagination or page resize action

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy , I'm considering making a Color Picker for this view like the select box shown in the wireframe above. If I did, I could use all colors recognized by name in CSS. Any thoughts? Is this too many options?

Right now it would just be manual text entry as it is currently. It can always be improved later if you'd rather save it as a future improvement. 

https://www.w3schools.com/cssref/css_colors.asp

**Comment by YoMurphy** [comment]
My thought would be to consider this a future improvement.  I presume 
that color changes may only occur to help indicate a major development 
change or platform change to the end user.

*/Rick Murphy/*
*Murphy Automotive, Inc.*
p: 	952-997-3310 m: 952-484-5302
w: 	www.murphyauto.com <http://www.murphyauto.com> e: 
rick.murphy@murphyauto.net <mailto:rick.murphy@murphyauto.net>

dba.
ProTech Automotive
Edina Tire & Auto
Grandview Tire & Auto - Vernon
Grandview Tire & Auto - Cahill

**Comment by DanielCaspers** [comment]
Opened #40 so we can come back to this idea later if we want

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , how do you feel about this for work description?

![image](https://user-images.githubusercontent.com/6056563/28101196-7f1e7f34-668c-11e7-9fbe-707009b857b0.png)

When we make it editable (eventually), it would just look like this when activated. 
![image](https://user-images.githubusercontent.com/6056563/28101236-ca53632a-668c-11e7-9c77-fd32e87730d2.png)

While all individual inputs appear selected, one can still tab through them individually. I just have to label the fields independently (e.g. Work Description Line 1, etc) if we don't like them looking selected all the time

Right now its just always disabled, regardless of the lock.

**Comment by DanielCaspers** [comment]
Pushed to stable in case you want some hands on time with it. Please also check out work orders with no work description. Would you like a label with no content below it, or no work description label in the first place?

**Comment by DanielCaspers** [comment]
Another option is available on Weekly where I've centered the work description to make better visual use of the card space. Because of the length of work description lines, it won't take up the full view at this time

![image](https://user-images.githubusercontent.com/6056563/28101825-af25307a-6690-11e7-9669-1f94e6d6949c.png)

Looking forward to hear if left adjusted or centered is preferred.

**Comment by scaspers** [comment]
I think that either would work but might prefer left justified.
Side Note: To the left or right of the work desc may be a good location for the RS and History buttons??

**Comment by DanielCaspers** [comment]
Yes, we can put those buttons on the side of desc

**Comment by DanielCaspers** [comment]
@YoMurphy @scaspers,

I am looking for some more feedback on the content and the look/feel of the recommended services dialog. I have a few style proposals to get you thinking.

1) Icons for RS Level (1-5)
![image](https://user-images.githubusercontent.com/6056563/28447272-628f1742-6d95-11e7-8a8e-6faaa0c90baa.png)

**Comment by YoMurphy** [comment]
@DanielCaspers @scaspers 
Here are a few suggestions for each level. They seem to make sense in my mind at least. I can make you specific icon files or special sized images. Just let me know the image requirements.
![rs_icons](https://user-images.githubusercontent.com/25590044/28532707-372f8e38-7060-11e7-9b8d-9d963bffff55.jpg)

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , 
They make sense to me too.

That is essentially what I've done, I'm just picking from the [Material Icons Library](https://material.io/icons/), which is what Google does in all of their products, including Android OS, so it should have a familiar look and feel to users. No need for custom icons from you guys.

How about I just change the calendar above from green to blue, and then maybe find a different Notes icon? There are some like Assignment, Description, etc, that are similar. My only slight concern is that I don't want to overload any vague concepts with the same icon, since I already was using the Description icon for RecommendedServices. 

Since we seem to be on the same page, I'll keep with just the icons then for Recommended services and skip the text in this view.

**Comment by DanielCaspers** [comment]
Also, in case I was too vague before, in my screenshot above, I was displaying from top to bottom my recommended icons for

1. Immediate
2. Moderate
3. Should Watch
4. Maintenance
5. Notes

**Comment by DanielCaspers** [comment]
App is updated to include latest icon decisions, which struck a good medium between intent of all first pick icons without needing to integrate a sprite sheet (which wouldn't be bad if we needed too, but material icons are VERY easy).

Currently they display on stable/weekly/nightly-a using random number generation until D3 issue #8 is extended just so you can cycle through the icons if you want to see soon.

**Comment by DanielCaspers** [comment]
Here's what it looks like now. This is pretty close to your tablet specs. 
![image](https://user-images.githubusercontent.com/6056563/28741435-80db5318-73db-11e7-9a26-ec90cc572f22.png)

![image](https://user-images.githubusercontent.com/6056563/28741440-93004de6-73db-11e7-8e88-722dca5b9639.png)

**Comment by DanielCaspers** [comment]
Available to play with on "Stable"
