### ISSUE TITLE
Work Order - Inspection Tab

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#42]
Implement page https://drive.google.com/drive/u/0/folders/0B9irLMSVERqNRzFKOE53TXZtQ0U

1. ~~Display cards in pleasing format, grabbing all available checklists to pick from~~
2. Write controller layer for linking a work order to an inspection
3. Write database relationships and model relationships needed to "marry" an inspection and a work order
3.1 Consider the case of allowing multiple checklists to be completed for a given work order.
3.2 The same set of checklist items should in some way be shared amongst multiple checklists. How the validation policy applies is TBD. 
3.3 A tech should not have to re-note the status of an item which has already been completed under a different checklist of the same work order. This was brought up as a "Did not inspect" option in #62

**Comment by DanielCaspers** [comment]
@YoMurphy @scaspers, what do you think? Hopefully this raises some spirits to see us finally get here! This is at 768px, so presumably that is portrait mode on your tablets? I can't quite remember...

_This is only a very modest beginning._ 

![image](https://user-images.githubusercontent.com/6056563/30044350-38f5f9f4-91c2-11e7-8949-d44654a4bda7.png)

**Comment by YoMurphy** [comment]
Looking good Danny! 

Do you think we should consider icons for the Condition column rather than the text to conserve more space so see more Description? Similar to our RS icons or possibly the same.  The GOOD icon could be a simple OK, Star or Thumb Up icon from the Material Icons. I'd leave N/A as is.

**Comment by DanielCaspers** [comment]
@YoMurphy, I like that idea to save screen real estate so long as you are ok with mixing the notion of recommended services more with the inspection.

AFAIK, customers would probably think a recommended service is any inspection item that wasn't "Good".

@scaspers, thoughts?

**Comment by scaspers** [comment]
@DanielCaspers @YoMurphy 
I believe the RS icons are a good idea.  Dan, we should talk again for a few minutes to go over the expected flow again as it was some time ago that we came up with the wire frames.

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy ,
I made lots of minor tweaks and polish to condition and level of concern. The condition/level of concern control now knows how to make selections mutually exclusive. The notes dialog and photos dialogs are shelled out to give the rough idea.

Up next is making a measurements dialog. 

The updates are available on all 4 servers. _Remember to hit `ctrl+f5 or Empty cache and Hard Reload`_

Hope you guys enjoy :)
![digitalinspection_conditionorlocmutualexclusion](https://user-images.githubusercontent.com/6056563/30410897-5cafd9e2-98d3-11e7-8464-78a3391342c0.gif)

**Comment by DanielCaspers** [comment]
As a separate note @scaspers , I shied away from doing a "dropUp" on Canned Responses, because that would block the current row's notes/photos box. I say that would be one of those things where we'd give users a tip that they can click on the next row's condition/level of concern control to continue for fast navigation. They could click on any open space, or the multiselect button itself, but it is ultimately a "wasted click".

**Comment by DanielCaspers** [comment]
Hey @YoMurphy , @scaspers , a couple cool features went in recently. I think it's time to show the techs :)

1. Moved the buttons to the toolbar for a more premium experience similar to Google's tools. The buttons are accessed in the toolbar using row selection. A row cannot be deselected at the moment, but a different row can be selected instead, 
2. Measurements dialog is pulling real measurements related to a checklist item
3. I've added a [second icon library, Material Design Icons,](https://materialdesignicons.com/) to bridge the gaps in [Google's native lineup](material.io/icons). From here on out, this will be our 2nd choice when looking for those one offs we can't find at 

This is pushed to **weekly**.

![dynamicmeasurementdialog](https://user-images.githubusercontent.com/6056563/30528985-187d404c-9bfe-11e7-9d68-d14441e24ab2.gif)

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy, I'll be starting on database design next for making all the stuff in the UI work for real.

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , I'd like to think that I had a breakthrough on the database design tonight. Thank the Lord :) There are still some important details pending, but I think I have a decent vision for how we'll do this. I made a [UML Class Diagram](https://www.lucidchart.com/pages/uml/class-diagram) to show what I'm thinking. **Don't let the formality of the diagram scare you off!**


[Draw.io online drawing tool link (connected to Google Drive)](https://drive.google.com/a/caspersonline.us/file/d/0B9irLMSVERqNN0czTzgwMEpOMTA/view?usp=sharing).


[PDF copy on our Google Drive folder](https://drive.google.com/a/caspersonline.us/file/d/0B9irLMSVERqNT3BJemd6Y3NhRkk/view?usp=sharing)

I've outlined some areas I'd like you both to take a critical look at to see. It's fine if you don't have input on some of them; I'm just trying to smoke out issues early because database work is harder/ more time consuming to change later than other types of application rework.  _As always, any feedback is welcome_
1. Do you see any potential design flaws? Are the relations incorrect? Is the multiplicity (one-one, one-many, etc) correct for all entities?
2. Does this model the real world as accurately as possible? If not, how can we improve?
3. Do we need to track more data in more places? 
4. Do you have concerns as to how this will handle checklist items from multiple checklists in a single inspection for a single work order?
5. Would you like to see more data or classes on here to get a better idea of the bigger picture? 
6. Are there any use cases you don't think this will handle? If you aren't sure, just post them back for me to ponder! 

Thank you for your continued patience!

**Comment by DanielCaspers** [comment]
@scaspers, many of the improvements you suggested recently were brought into stable in commit 2529cd4 . Feel free to take a look if you like.

**Comment by DanielCaspers** [comment]
Hey @YoMurphy , @scaspers , 

Here's whats now going into the DB. This is not live on the staging servers.
1. Conditions
2. Canned Responses
3. Notes
4. Measurements

So, these now persist on refresh, etc, as expected. 

Next up: Photos need to be persisted, and viewable with that dialog
On Deck: Merging Inspection work together every time an Inspection Card is (Oil Change work transfers to Techs, vice versa)

**Comment by DanielCaspers** [comment]
Hey @scaspers , @YoMurphy ,

Photos are now persisted too! Not live on the staging servers yet, but here's a GIF showing that its becoming very real.
![digital-inspection](https://user-images.githubusercontent.com/6056563/33792254-4f70c25c-dc60-11e7-8420-097f4ba7e08a.gif)

Next up: 

1. Merging Inspection work together every time an Inspection Card is (Oil Change work transfers to Techs, vice versa)
2. Syncing up the staging server database, perhaps on the final machine.

**Comment by DanielCaspers** [comment]
@YoMurphy @scaspers , do I have something special for you two :) Go check out nightly-a or nightly-b

Scrollable Tabs are in for filtering checklist items to perform by tag. _This is a big gif, so let it load before you watch it._

![di-scrollabletabs](https://user-images.githubusercontent.com/6056563/34073612-b0d4aeca-e262-11e7-8c17-8a70da6eef71.gif)


Features:
- No scrolling arrows when all tabs fit
- Touch devices allow dragging left/right through tab container to navigate quickly
- Desktop devices have "hold and release" scrolling" for quick movement, or single click for precise movement.
- Carets are disabled when you've reached the end of the list. _There is no circularly linked functionality in the plugin._

I'm calling the initial implementation of the Inspection Table done. Any future improvements, or bugs discovered should be logged in a separate task for better traceability. It's been half a year. time to close this!
