### ISSUE TITLE
Confirm Leaving Unsaved Changes Dialog for all Forms

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#43]
__Motivation__
A user should be made aware that they have attempted to leave any page which they had manipulated and not saved the state of. 

Look and feel should be similar to our other dialogs.

---
Discard changes and leave page?

 CANCEL                    DISCARD

---

__Technical Notes__
https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by scaspers** [comment]
Also, remember to release file lock(s) if PICK data was being edited and user chooses to discard.

**Comment by DanielCaspers** [comment]
This is what I am planning on doing next unless anything more urgent comes up

**Comment by DanielCaspers** [comment]
This will not work for customer or vehicle form yet until a separate bug is fixed that has to do with how the page is loaded in the first place. However, all Checklist creation forms have this behavior, and all new forms will have this behavior too!

Accidentally closed from commit message using #48 .
