### ISSUE TITLE
Customer & Vehicle forms edit mode contrast

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#48]
Make it more noticeable that the user is in edit mode by altering font color or bordering form or ???

**Comment by DanielCaspers** [comment]
This has been bugging the crap out of me too. I'll override the library CSS

**Comment by DanielCaspers** [comment]
@YoMurphy , @scaspers , hows this? I'm gonna push it to stable before leaving so you can see for yourselves too.

![jul-1-2017-8-25-am](https://user-images.githubusercontent.com/6056563/27762408-2aad859c-5e37-11e7-94d7-3a904d100d2a.gif)

**Comment by DanielCaspers** [comment]
If you all have different styling ideas, I'm just restyling each individual form field with CSS. Any other tweaks or comments are welcome to add to the CSS rule.

```
.form-control[disabled], 
.form-group .form-control[disabled]
{
    color:rgba( 0, 0, 0, 0.4) !important;
}
```

**Comment by DanielCaspers** [comment]
Updated to 0.6 on nightly b

**Comment by DanielCaspers** [comment]
How about this? 

![image](https://user-images.githubusercontent.com/6056563/28096672-41934b8e-6670-11e7-8fac-11d36a943459.png)
