### ISSUE TITLE
Release work order lock on navigating away

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#50]
*Motivation*
1. ~~A user with no modifications in the edit mode of Vehicle or Customer tab should have their file lock released when they navigate away as a courtesy to other users of the system.~~

Depends on https://github.com/scaspers/D3-API/issues/13
2. Two or more users of DI requesting a lock on the same work order should not be allowed. In such a case
2.1. The first user to request edit rights to the work order
2.1.1. Receives edit privileges and the ability to save new data
2.2. Any subsequent users who request edit rights to the work order while it is locked
2.2.1. Receive an error toast indicating that the work order is locked and has functionality that redirects the user back to a view only copy of the work order.

*Technical notes*
https://stackoverflow.com/questions/735350/how-to-get-a-users-client-ip-address-in-asp-net

To limit the number of places a user could navigate away to once they have a lock
aspx?_ViewStart+cshtml+and+conditional+Layout+pages

**Comment by scaspers** [comment]
Maybe we can use a server managed session ID in place of the IP address or have the server (PICK) that is managing the Auth actually save active auth tokens as session ID's??

**Comment by DanielCaspers** [comment]
Do you have a specific reason or use case in mind for that? Are you thinking multiple instances of DI being run from the same IP? Just trying to understand if you feel client IP vs session ID  are equal alternatives in your mind, or feel session ID approach has more merit.

**Comment by scaspers** [comment]
The only reason is for ability to access the server auth with WWW internet addresses that can often be devices behind a NAT firewall sharing the same address.  It may not matter as long as we don't have multiple logins from the same user but if we want to allow that then we could easily have conflicts.

**Comment by DanielCaspers** [comment]
If you still want to display machine IP information in the toast, we will have to pass that anyway and could lock based on that initially. 

Alternatively, we could just say that a certain employee id has it locked, but that doesn't ensure uniqueness with multi client either. Not sure how we'd communicate that error though.

**Comment by DanielCaspers** [comment]
@scaspers , if you are interested in trying, I pushed a very alpha version of this to nightly A. Remember to empty cache and hard reload. 

To see if its working properly when playing with the green screen, try the following.

1) Go to the _vehicle tab_ and enter "edit mode" (temporarily only implemented here)
2) Make unsaved changes
3) Attempt to leave unsaved changes by selecting a new tab
Expected result: Navigated away and lock is released. 

It's late, so I didn't look too closely, but based on the headers, I think we are in business :) Check my work?

**Comment by scaspers** [comment]
After making unsaved changes I selected the customer tab, i received the alert warning, selected discard and the page returned was the vehicle tab. (Locks were removed! yea!)
I assume that you asked me to select another tab because you knew that the <--- button would not have the same behavior.

**Comment by DanielCaspers** [comment]
@scaspers, yeah. I am trying to make sure that the back event wasn't cancelling my HTTP request. I was having more luck testing the tab-away case. I'll obviously continue working on it, but glad to know a rudimentary version of it works :)

**Comment by DanielCaspers** [comment]
We will be taking a new approach. No more work order locks for DI for now!

This issue is now awaiting https://github.com/scaspers/D3-API/issues/16 for completion
