### ISSUE TITLE
Changing Inspection Item's Level of Concern should update available Canned Responses

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#59]
**Motivation**
The number of total available canned responses for a given checklist item could be > 100, and will likely have a few items with > 20 . To reduce the need to scroll and search for the item a user should only see the items applicable to the level of concern they selected.

**Relationship**
1. A canned response applies to 1 or more levels of  concern (a.k.a RecommendedServiceSeverity)
2. A level of concern in an inspection will have 0 or more available canned responses. 

**Implementation**
1. ~~Add configuration option per each canned response to make it apply to one or more levels of concern.~~
2. ~~Save list of severities to the database as a serialized string.~~
3. ~~Send response to server on changing inspection item condition~~
4. ~~Use Bootstrap MultiSelect's 'dataprovider' function to give updated CannedResponses OnSuccess of the Inspection Item Condition POST request.~~
5. Perform DB migration on server.

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , feel free to double check over "relationship" header in description to make sure the expected behavior lines up with what you were thinking. I think it should do just fine though.

**Comment by scaspers** [comment]
looks accurate.

**Comment by DanielCaspers** [comment]
Hey @scaspers , @YoMurphy,

Filtering canned responses by condition is coming along nicely. Almost finished the full feature all the way through. However, since there are DB changes I can't push this to the live server without a sync up.

The image below shows the update to the Checklist Item configuration screen. 

![image](https://user-images.githubusercontent.com/6056563/33001591-76460112-cd74-11e7-86e2-b5eaccef2545.png)

I also have the filtering logic all set to go. Now its just a matter of changing the values in the dropdown to use the new filtered ones. 

**Notes to self for finishing dynamic dropdown:**
1. http://www.mikeyd.com.au/2009/08/22/dynamically-populate-a-selectdrop-down-list-using-aspnet-mvc-jquery-and-json/
2. https://stackoverflow.com/a/28117352/2831961
3. https://stackoverflow.com/a/34048559/2831961

**Comment by DanielCaspers** [comment]
Database migration went without a hitch :)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy FYI this is available on all 4 servers now.

**Comment by DanielCaspers** [comment]
Notes I forgot to add in the commit message for future reference

- Front End: Uses Bootstrap-MultiSelect 'dataprovider' to insert filtered items
 OnSuccess of the inspectionItem condition POST request

- Back End: CannedResponse.LevelsOfConcern is a list of RecommendedServiceSeverities. 
This list is saved in the DB as a delimited string to prevent adding another DB table. 
Special serialization/deserialization logic is required.
