### ISSUE TITLE
Inspection table layout - tech comments

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#62]
# Summary
- They all feel that either one they will get used to and struggled to choose one.
- The 5 that did vote, voted for the 3/2 for option 1. @scaspers  and @YoMurphy  also prefer Option 1 for fluidity

### Option 1 - Buttons in row
After showing to 7 techs we have this:
- "it was more fluid" (heard this comment 3 times)
- Thought that it would be nice if the icons for (measure, notes, picture) would change if they already had values.

### Option 2 - Buttons in toolbar
- cleaner appearance.
- They hoped for the ability to see in the table if they had already (snapped picture, left manual notes, done the measurement)

# Action Items
- [x] The text from the canned responses should be omitted and replaced with icon instead to create space.
- [x] Each dialog from the inspection view should show the associated checklist item.
- Asked about a "Did not Inspect" option
-- Approach TBD. See comments

**Comment by DanielCaspers** [comment]
@scaspers, @YoMurphy , could you fill me in on the reason for adding a "Did not inspect" option as a level of concern? I'd like to understand the difference between this and N/A? Is this to let them come back to something later?

**Comment by DanielCaspers** [comment]
This is the new look for canned responses. Always shows the number of items selected, so it starts at 0 and the caret. 

![image](https://user-images.githubusercontent.com/6056563/30777773-3d61ff68-a088-11e7-846a-174e791e3e87.png)


![image](https://user-images.githubusercontent.com/6056563/30777764-203e630e-a088-11e7-9b10-7857d04632e8.png)

**Comment by DanielCaspers** [comment]
Dialog titles now show the checklist item name at the end, like so.

![image](https://user-images.githubusercontent.com/6056563/30777931-2b31183e-a08c-11e7-9f7e-0f3d58e91e29.png)

**Comment by DanielCaspers** [comment]
All currently addressable issues have been solved, and the remaining model design question has been moved to the appropriate task.
