### ISSUE TITLE
Customer Facing Inspection Report

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#64]
**Motivation**
As a customer, I would like to see the results of the inspection performed on my vehicle after a service. This should be made available as a public webpage for viewing on mobile, tablet and desktop form factors.  

**Wireframes**
Questions before proceeding. 
1. How should we group / aggregate the various inspection items in a work order? By customer concern, RS level, both, etc. 

2. What **InspectionItem info** will we need?
 - Inspection Item Name
 - Condition
 - List of canned responses that apply
 - List of inspection measurements (name and recorded value)
 - List of photos
 - _Inspection Item Note_ Is this for internal use only?

3. What **non inspection item info** will we need? 
 - Work Order Number
 - Technician number, or name who worked on it. Should we support multiple techs attached? How does work order do that?
 - Date completed (same as work order)
 - Customer name
 - Customer vehicle year, make, model, color

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy,

Here are some questions we'll need to be able to answer to move forward. If you find that its easier to answer these by prototyping UI designs on paper, by all means go ahead and scan me what you come up with. You can attach images to here. 

As a reminder, this will be rendered as a _totally separate webpage_ and not within DI app itself.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy Any update on this? I was thinking this would make the most sense for me to work on right around the new year if direction from you guys is available by then.

**Comment by YoMurphy** [comment]
Here is some initial thoughts on layout on what I suspect will be the most popular viewing device, the cell phone. Unclear still about sorting ability in customer view, possibly by some new tags. It would be a nice function. Standard Sort, Customer Concern, RS Level. Standard Sort= UnderHood, UnderCar, Fluids, Battery, Tires and Brakes. Also when or where might we add additional items we had previously talked about.... How to indicate Estimated items, show dollars and/or estimate details. An approval check box, Approval totals and Submit Approval. Maybe these thoughts are just possible future improvements.
![inspshow](https://user-images.githubusercontent.com/25590044/34128016-dac1efce-e404-11e7-9f81-4f9fe26b9afe.jpg)

**Comment by DanielCaspers** [comment]
@YoMurphy , thanks for the initial thoughts. Looking forward to hopefully talking in person soon to iron out more of this. 

Thanks for bringing up items such as how estimates tie into this. That might play a pivotal role in how we make this all available to the customer from a technical standpoint.

As far as attaching ourselves to specific UI components/concepts, I'll drop this in here since it came up in conversation with @scaspers . Both are long reads, and I've only speed read both in the past, but very valuable. This isn't by any means to steer us out of accordions, but rather guide us to why we should or shouldn't use them for our case. 
1. https://www.nngroup.com/articles/accordions-complex-content/
2. https://baymard.com/blog/accordion-and-tab-design

**Comment by DanielCaspers** [comment]
Hey @YoMurphy, @scaspers ,

Go ahead and check out the alpha version of the inspection report.

To see an example, here is the style of link we will generate for the customer to go to. Go ahead and click on it. 

http://ca2.murphyauto.net/#/inspections/004584155/report

A couple notes about this URL:
1. **This will not have a work order ID in the URL once this goes live to customers**. Instead, that will become the inspectionId Guid, which will be impossible for a malicious user to guess, unlike a work order id. 
2. It needs the hash in order to work and reload properly. The entire customer app will live under the /#/ portion. 
3. Right now, navigating to just http://ca2.murphyauto.net/ brings you to http://ca2.murphyauto.net/#/inspections, but since no ID is provided, there is no data. If you'd like, we can handle this empty state differently, but we won't be giving customers this URL directly anyways like that. 

@scaspers, when showcasing what we have so far to Rick, keep in mind the following changes/fixes since I last showed you.
1. Reloading table or report works
2. It is fetching any work order from the URL that DI server knows about
3. The issue with the Image Gallery from the table view has been fixed.

**Comment by DanielCaspers** [comment]
Hey @YoMurphy, @scaspers , better head over to ca2 and see the new facelift I put in. The inspection item grouping is now real also.

**Comment by DanielCaspers** [comment]
I will be waiting to hear of any proposed layout improvements, or bugs you find. 

Once you guys feel relatively confident it's everything you hoped for, I'll go ahead and close this.

**Comment by YoMurphy** [comment]
What an incredible job so far! I've made a bunch of notes on the images attached. All are just my suggested improvements and certainly open for discussion. Let me know if you have any questions. 

-------- Original message --------From: Daniel Caspers <notifications@github.com> Date: 1/7/18  8:12 PM  (GMT-06:00) To: DanielCaspers/DigitalInspection <DigitalInspection@noreply.github.com> Cc: YoMurphy <rick.murphy@murphyauto.com>, Mention <mention@noreply.github.com> Subject: Re: [DanielCaspers/DigitalInspection] Customer Facing Inspection
  Report (#64) 
I will be waiting to hear of any proposed layout improvements, or bugs you find.
Once you guys feel relatively confident it's everything you hoped for, I'll go ahead and close this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielCaspers/DigitalInspection","title":"DanielCaspers/DigitalInspection","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielCaspers/DigitalInspection"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielCaspers in #64: I will be waiting to hear of any proposed layout improvements, or bugs you find. \r\n\r\nOnce you guys feel relatively confident it's everything you hoped for, I'll go ahead and close this."}],"action":{"name":"View Issue","url":"https://github.com/DanielCaspers/DigitalInspection/issues/64#issuecomment-355872852"}}}

**Comment by DanielCaspers** [comment]
@YoMurphy please attach images directly through GitHub. I cannot see your attachments.

**Comment by YoMurphy** [comment]
![screenshot_20180108-093850](https://user-images.githubusercontent.com/25590044/34680126-bbd70702-f45d-11e7-9c74-26f15ef5832e.jpg)
![screenshot_20180108-094337](https://user-images.githubusercontent.com/25590044/34680127-bbefa6f4-f45d-11e7-968e-4c10923ff98a.jpg)

**Comment by DanielCaspers** [comment]
@scaspers, @YoMurphy, your wishlist has been fulfilled. I made two deviations for UX reasons which we can always revisit later if you're strongly against.

1. **I only shaded the expandable header gray on both tabs**. The applied color in all others states is has been corrected (_except the blue tap animation for opening accordion in "By Area" tab. I don't have control over that without modifying library source code.[ I've opened a support issue in their library](https://github.com/swimlane/ngx-datatable/issues/1224)_).  I feel this will provide a better separation of headers vs items. To further separate the items from other items in the accordion, I changed the divider to be a more opaque black. 

![image](https://user-images.githubusercontent.com/6056563/34702670-a59afc9e-f4b4-11e7-858a-a1ff99a561bb.png)

The code is dead easy, so let's make the divider more obvious to separate the items from eachother instead of more background-colors? Go ahead and tweak it in the element inspector in your browser to your liking and report back if you're not quite happy with it.
`
.ma-divider {
    display: block;
    border-top: 1px solid rgba(0, 0, 0, 0.24);
    margin: 0;
}
`

2. **I made the view images button include the icon**. I feel a large number of people will recognize this icon, given its vast presence in the Android and Google ecosystem, and it draws the eye on an otherwise text-heavy page. I see benefit in keeping it until we hear otherwise from users. 

Once you've had a chance to demo this, either report back with more things to change or close this.

**Comment by YoMurphy** [comment]
Excellent job Daniel and crazy fast. 
1. I still feel the 2 sort tabs should be more uniform. To simplify my thought, the only difference between the 2 Sort tabs is the Grouping. The only visual change should be the Group headers. (I suggested a darker grey shade) The Checklist item label header in light grey should be uniform between both sort views.
1.5. Can the 2 sort views share the same CSS to ensure their symmetry?
2. The expander icon on the Priority tab is non-responsive. (You can click anywhere to expand in the header but the expander icon itself.)
3. The header and footer labels on the Priority tab (Condition, Name, Selection/total) seem unnecessary. Do they have a purpose I am unaware of?
4. Margins, Left and Right, on the expanded description view of the Priority tab are minimal and great. The Area tab margins can match. 
5. When expanding an Area view Group, the concern icon disappears, the header grows in size and I think it should actually shrink.
Let me know if any of this needs any clarification. Feel free to call me anytime. Thanks

**Comment by scaspers** [comment]
I noticed that on the Priority tab the sorting is allowing null conditions (level of concerns) to float to the top and appear as NA and items that are set to NA items appear at the bottom.  Should null values just be excluded?

**Comment by DanielCaspers** [comment]
Rick, thanks for the thorough feedback.

1) **I can do that, but lets wait until you've demoed to others before we make the switch. Ask around to see if we users would benefit from search in that view.**

The reason I implemented the feature differently was because the "By priority" uses a table plugin, which would allow more advanced operations later on, like search. If we don't discover a need for search when discussing with users then I definitely agree. 

2) I will fix, whether its fixed by me changing how I use table plugin, or switching to accordion.

3) Can remove regardless of implementation decision quickly.

4) I'll resize the margins.

5) The accordion does this by default when it animates. We can fine tune it with ease, but I have to imagine Google made it expand for user experience reasons, because its easy to get lost in all the content of an accordion. Would rather leave TBH. 

**Planning to hold off on further changes until we have a large round of user testing data back from you guys.**

**Comment by DanielCaspers** [comment]
Table header and footer removed for by priority. Awaiting further user feedback before changing away from table for the accordion.

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy the latest is available on nightly-b, since that is where ca2 is pointed right now. 

1. Applies CSS uniformity by nature of using the same accordion component for both views (no more table).
2. Expander icon click is responsive (see 1)
3. No header/footer (See 1)
4. Margins cut in half from 24px to 12px for these 2 accordion bodys. I think we should still leave some for users using edge-to-edge phone displays. 
5. **Did not change animation height on accordion**. It's [pretty easy to configure](https://material.angular.io/components/expansion/api#MatExpansionPanelHeader), but I'm gonna trust Google's usability team on this one. I think the animation gives the content under view prominence and focus, and makes the app seem more lively. Happy to change later if either of you feel strongly against this.

Add'l updates
- Items with unset conditions will not show up in the customer view

Future improvement suggestions are welcome as always, but this ticket had too large of a scope and needs to be done. Here's to celebrating only 9 remaining tickets for launch 🥇
