### ISSUE TITLE
Inspection - Canned Responses can't go from N to 0

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#66]
**Problem**

1. Go to an inspection to perform for some work order. 
2. Select a condition for an inspection item
3. Select one or more canned responses for an inspection item
4. Deselect all inspection items.
5. Refresh page.

**Expected** # Canned Responses for inspection item should be 0.
**Actual**  # Canned Responses for inspection item is > 0 .

**Workaround**
Instead of deselecting from the dropdown, select a new condition and reselect the desired condition.

**Technical notes**
This appears to be a feature of the model binder in the view. It prevents form submission from turning into an HTTP request when the select box is empty. Perhaps we need a non-user facing default value?

**Comment by DanielCaspers** [comment]
Note to self

Looks like one solution would be the client substituting an agreed upon bogus value that the back end transforms after receiving submission

See bottommost code exanple
https://www.telerik.com/forums/posting-form-with-empty-multiselect

**Comment by YoMurphy** [comment]
Note to self

Ignore "Note to self" comments made by @DanielCaspers ;) lol

**Comment by DanielCaspers** [comment]
Lol. If you'd like @YoMurphy , I can be much more diligent about using the @ syntax so you can change your settings as I've highlighted.

![image](https://user-images.githubusercontent.com/6056563/34850965-932ade4a-f6ed-11e7-93e9-86baac408a55.png)

With that setting you are auto-notified once you have commented once on an issue, or until I rope you in.

**Comment by YoMurphy** [comment]
@DanielCaspers , I like seeing all the comments, especially the ones that make me laugh. I just wanted to share with you the humor I found in it. Keep up the great work!
