### ISSUE TITLE
DI2 - Sys Is Not Defined

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#68]
**Problem** 
When changing a condition or canned response on an inspection item, a console error is shown. Its seems to be a high level issue. 

**Differences between DI and DI2 servers, respectively**
1. Apache version
1.1 2.4.6
1.2 2.4.29
--- the apache versions were the same until DI was updated about 7 days ago (long after problem was noted)

2. Apache configuration for nightly-b folder
2.1  Servername 10.13.0.122
2.2 Servername di2.murphyauto.net and SSL

3. Mono version 
3.1  5.4.1.6
3.2  5.4.1.6

4. C# compiler version
4.1   gcc -v  4.8.5 20150623;  mcs --version  5.4.1.6
4.2   gcc -v  4.8.5 20150623;  mcs --version  5.4.1.6

20180122 - Things tried with no joy:
-toggling the key in Web.config "UnobtrusiveJavaScriptEnabled"
-changed the apache repo on DI to match DI2 now both are on 2.4.29

**Comment by DanielCaspers** [comment]
@scaspers make sure that all of the javascript files have copied over successfully. It struck me that its possible the copy failed, and that one of the files here did not get sent to the browser.

https://github.com/DanielCaspers/DigitalInspection/tree/master/DigitalInspection/Scripts/Library/JQuery-Ajax

**Comment by DanielCaspers** [comment]
New suspected root cause is due to differences in apache server versions between two boxes.

**Comment by scaspers** [comment]
loaded apache2.4.6 just like staging but with php.  Same results.  Cannot uninstall php because the D3-API requires it and DI requires the API.

Upon looking at the complaint "Sys is not defined" I see that the code\html is not delivered the same between the two servers for the file:
/nightly-b/Inspections/Index?workOrderId=004584156&checklistId=a0d1155a-992d-475e-9bb9-b55938130ef2



P

**Comment by DanielCaspers** [comment]
@scaspers , I got a [new lead from digging](https://www.telerik.com/blogs/common-reasons-for-the-lsquo-sys-is-undefined-rsquo-error-in-asp-net-ajax-applications).

>5)  The virtual directory in IIS is not marked as Web Application. Converting it to Web Application should fix the problem. 

Please verify that the folder configurations on Apache are _identical_. I'm assuming there are similar distinctions which might be possible in Apache as there are in the case of IIS. 

If that's not the ticket, please fill in the numbered list I've added to the description for troubleshooting sake. 

I've also taken a look down to the level of the Web.config file governing the nightly-b app and just re-pushed that and verified the proper lines exist there, but still no go from my side.

**Comment by scaspers** [comment]
I tried configuring without a server name (use IP only) and without SSL with no change.  
Found a missing symlink /usr/bin/mod-mono-server2 and added that with no change.
Verified virtual server setups for www & /nightly-b made changes to the order of config items with no change.

**Comment by scaspers** [comment]
Is this error message from the server log helpful?

> WARNING: WebConfigurationManager's LRUcache evictions count reached its max size
Cache Size: 100 (overridable via MONO_ASPNET_WEBCONFIG_CACHESIZE)

**Comment by scaspers** [comment]
Ideas from searching:
https://stackoverflow.com/questions/7015526/asp-net-mvc-3-unobtrusive-jquery-client-side-validation-with-child-collections

https://stackoverflow.com/questions/17974825/simple-mvc4-unobtrusive-ajax-not-working

*****  Not needed.... IT'S WORKING NOW!!

**Comment by DanielCaspers** [comment]
@scaspers, if you think of anything else to put in Web.config, know that it is dead simple. Check out the above commit if you'd like to know for your own sake. Actual key access is a one-liner.

**Comment by DanielCaspers** [comment]
@scaspers , assigned to you to close once we safely have production instance in place with no mono/apache issues.

**Comment by scaspers** [comment]
Have set up mono on MAIL2 with no issues.  I will be loading on production box in the next 10 days but feel this is resolved.

**Comment by scaspers** [comment]
This issue resurfaced when installed on MAIL2.  Again tried many things with no joy.  Finally tried it by running xsp4 --port 9000 in the app directory and that worked fine.  Then I tried accessing through apache proxypass and that worked fine.  Then I tried again through apache/mod_mono and it now works.  Not sure what fixed it, maybe when xsp4 ran and compiled it fix some unknown background issue.  Hopefully this does not re-occur.

**Comment by DanielCaspers** [comment]
To me, this sounds like what happened last time.

**Comment by DanielCaspers** [comment]
Original email notes.

> Not sure what happened but IT WORKS!
>  I was trying it with the /test server and used xsp4 without apache and that was working better (home page rendered).
> Then I put it back in apache and it now rendered correctly.
> I then had problems with DI not loading at all and I copied nightly-b from DI1 and pushed it to DI2 (in nightly-a & nightly-b)
> It now works!
> I am very very afraid though:-\
