### ISSUE TITLE
A method to delete inspections when a work order is deleted from PICK

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#70]
When a work order is deleted from PICK we should have a process that would check for a related inspection and delete it also.  Can there be API access to a delete function?

Also, will there be a method to finalize or block changes to an inspection.  When an invoice goes to history on our system it might be a good idea to lock further changes to the inspection as well.

**Comment by DanielCaspers** [comment]
Notes for other requirements for when we do this.
1. All client inspection page handlers must include HTTP 404s with an error handler that allows us to be redirected to the work orders table if the inspection is deleted. 
2. Delete must cascade the delete through all items related to an inspection.

**Comment by scaspers** [comment]
Maybe this can be accomplished by having a function that can reset or clear an inspection.  This could be used when an inspection, InspectionChecklistItems, measurements, images or note become corrupt.
An admin user would have access somehow reset an inspection to empty or deleted?

**Comment by scaspers** [comment]
Until we have a process for this we can edit the WorkOrderID in the Inspections table by changing the first three digits from the company number to '999'.

**Comment by DanielCaspers** [comment]
@scaspers please read commit comments and play with this. https://github.com/DanielCaspers/DigitalInspection/commit/4d429945dd02f9e2d191eb2fd2eb1c12683dae92

Let me know if you'd expect any different behavior or structure from the API. If you'd like, I can also make an endpoint that takes an array of workOrderIds so you only send one HTTP request. 

Once you give a go/no-go on how the API looks/behaves, I'll close this.

**Comment by DanielCaspers** [comment]
Closed on accident. Meant to close #77...

**Comment by DanielCaspers** [comment]
@scaspers you will now need this in order to delete inspections. Value will be compared against the config file so put whatever you want.

```
  <!-- Used as a semi secure way to allow anonymous deletions -->
  <add key="DigitalInspection-AppKey" value="NotActuallyTheSecret.NotQuiteThatDumb : ) " />
```

You'll need to set a header with `DigitalInspection-AppKey` in order to complete successfully. It just has to match an equality check, so feel free to add spaces or whatever other obscurity suits your fancy.

**Comment by scaspers** [comment]
This was working but now I cannot make it work??
