### ISSUE TITLE
Go-to-market odds and ends

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#71]
- [x] CA-Portal should have the headers as an InjectionToken.
- [x] Work order ID in URL must be replaced with an Inspection ID for obfuscation.
- [x] Code review CA-Portal for possible security vulnerabilities and performance bottlenecks
- [x] Adjust app copyright
- [x] Discuss legal liability, and terms of use of code as professional marketing content
- [x] push InspectionId obfuscation changes in local branches for CA-Portal and DI.
- [x]  [secure app secrets in Web.Config by making a separate partial file that we NEVER check into source control.](https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure)
- [x] Code review Digital Inspection for possible security vulnerabilities and performance bottlenecks
- [x] Lock down CORS policy for DI and Apache. ~~Adjust CA-portal headers to final deployment URL for` access-control-allow-origin`~~ CA-Portal headers are overwritten by apache so no need to adjust Angular app. 
- [ ] @scaspers will scramble app key, app secret and database connectivity information so nobody can reconstruct access by historical digging on the public internet. He will notify @DanielCaspers with the scrambled info and I will reconstruct my local file to match his. 
- [ ] @scaspers will create DNS names for ca-portal to access production and test DI instances, so that the client assets can always have that hard-coded in and then the app can know what to access without serverside processing

**Comment by DanielCaspers** [comment]
@scaspers , @YoMurphy , I've been tying up some loose ends. Here's how I plan to both make and give you a URL to the inspection report from DI. If you'd rather just open the inspection instead of copy to clipboard, let me know. It'd be a simple swap if you have a preference for how to pass these links around.

![feb-6-2018-9_03-pm](https://user-images.githubusercontent.com/6056563/35896729-49585b9e-0b83-11e8-953b-1bbd36cfbc5f.gif)

**Comment by DanielCaspers** [comment]
@scaspers, here are the anonymous JSON endpoints now. There are 4 endpoints instead of 2. 

1. /Inspections/Report?inspectionId=63fda305-98a0-4245-901b-97f83e09504a
2. /Inspections/ReportForOrder?workOrderId=00458415
3. /WorkOrders/Json?inspectionId=63fda305-98a0-4245-901b-97f83e09504a
4. /WorkOrders/JsonForOrder?workOrderId=00458415

1/2 and 3/4 behave the same, but allow for adapting to taking in either the inspectionId or a workOrderId

**Comment by scaspers** [comment]
I believe the CORS policy has now been set on di2.murphyauto.net.  Currently limiting access to d3|d3-devl|ca|ca2.

**Comment by DanielCaspers** [comment]
@scaspers please lock down before you go public to keep us secure :)

**Comment by DanielCaspers** [comment]
@scaspers do you want me to keep this open? I have a new strategy for handling environments that I think you'll find convenient enough without going to the trouble of getting fancy with DNS entries. 

My environment changes affect both upcoming MyCar as well as the public inspection report.

**Comment by DanielCaspers** [comment]
@scaspers Do you want me to keep this open? Otherwise I'm closing it since I haven't seen a response in almost a year....
