### ISSUE TITLE
Evaluate Inspection Report Needs

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#72]
@scaspers, @YoMurphy,

I tried printing an inspection report with the UI we have today, after expanding all groups. Here's what it would look like.

[PrintToPDF.pdf](https://github.com/DanielCaspers/DigitalInspection/files/1613832/PrintToPDF.pdf)

**Is this sufficient for launching the first version** for the few cases where your customer requests a printed copy? 

I am trying to groom the issue backlog so we have a very clear picture of what is and what is not a launch concern so that we properly prioritize work and so I can update on project scope, timeline and budget.

**Comment by YoMurphy** [comment]
The look I think is sufficient for a first launch. It could be better tailored to a printed page later if we think it is necessary. It would be nice to compact it or organize it to always fit a single page. Is it possible to include the following functions for launch?
1) Can there be a "Print" link or icon that would expand all groups or expand all but Good? Making sure all the pertinent information makes it on paper without having to manually expand it all.
2) Could a print dialog add or include any company contact information?

**Comment by DanielCaspers** [comment]
@YoMurphy, we might as well at that contact information at bottom always, don't you think? Maybe in a footer (but you'd have to scroll to the bottom to see it? 

I can see about expansion for print mode, shouldn't be too bad. 

I have another idea for compactness.  Depending on what all needs to be in it, why not just use that table, but instead of the accordion-like behavior, it just becomes a proper table.

**Comment by scaspers** [comment]
Maybe the company contact info could be at the top right.  We should be able to include in print but not necessarily on the screen.

**Comment by DanielCaspers** [comment]
Depending on what print needs I might just bite the bullet and make a separate page since the underlying components and building blocks are reusable.

Please let me know what info you'd still want on each report item, and what all info you'd like regarding order, store, contact info, etc and I think it over.

**Comment by DanielCaspers** [comment]
[Was addressed here](https://github.com/scaspers/CA-Portal/commit/b80ba80d7b10efc8b8d1a634de9077a06821396c). 

1. This solution (media query based) only works for the "By Area" tab because the hide/show is CSS based.
2. "By Priority" would need a different solution as those elements are dynamically added/removed from the DOM on expand/collpase in the table plugin. 
3. If we end up switching to the accordion plugin for "By priority" based on user needs you guys find, then the current solution will work for both tabs with minimal tweaking.

**Comment by DanielCaspers** [comment]
@scaspers, for the endpoint that has the company info that you demoed to me, would it be possible to also make sub endpoints or a query param that accepts company number?

Thinking we should slim that data returned to customer view and save time on JSON building on PHP. 

Something like... LoadStoreData.php?conumber=004 returns { "coname" : "Protech"... Etc  }

**Comment by scaspers** [comment]
Here is the endpoint:
https://d3-devel.murphyauto.net/api/v2/conos/  (for all companies)
or
https://d3-devel.murphyauto.net/api/v2/conos/004   (for ProTech)

**Comment by DanielCaspers** [comment]
@scaspers, thank you!

Not sure if you have preference one way or another, but typical REST API convention is to only return the value associated with the key in a dictionary (when querying a single entry from an array/dictionary type), and not an object containing the key and value. So, you might consider returning just 
` 
{
        "coname": "Grandview Tire & Auto - Vernon",
       ...
    }
`
for Company 001. 

Either way you go is fine with me technically speaking; just a style thing.

I plan on hooking this up to the Customer Portal this weekend so that the image asset and the phone number are both dynamic based on the associated work order. 

If you or @YoMurphy are aware of what company info you'd like where in the print view, I'd like to put that in this weekend as well so we can close this.

**Comment by YoMurphy** [comment]
@DanielCaspers , I think at this point the customer knows who we are and where their car is. When this report is printed or viewed the information that a customer would want is dependent on how it's being viewed. On paper they would want to see our logo, our phone number and who to contact (Service Advisor). At the Top would be preferred. On their phone or tablet the icons are ideal at the top and should include our logo, email and phone. What about a text link... Is that a thing?

**Comment by DanielCaspers** [comment]
"On paper they would want to see our logo, our phone number and who to contact (Service Advisor). At the Top would be preferred"

Yup, thats in the plan. @scaspers will be adding support for service writer name on work order

"On their phone or tablet the icons are ideal at the top and should include our logo, email and phone. What about a text link... Is that a thing?"

If I am understanding you right, why not put an email icon up there that is a mailto link just like phone is a tel link?

**Comment by DanielCaspers** [comment]
https://material.io/icons/#ic_email

**Comment by scaspers** [comment]
The "text link" is a thing just like "tel:"  you can have "sms:" also.  I will add the sms number to the company data endpoint.
https://material.io/icons/#ic_message

**Comment by scaspers** [comment]
we could have email link also

**Comment by DanielCaspers** [comment]
Cool. Here's my revised plan for that now that I know SMS links are a thing :)

For the digital version, toolbar will have:
- Email icon (email)
- SMS icon ([message](https://material.io/icons/#ic_message) was my preferred also, but could do [textsms](https://material.io/icons/#ic_textsms)or [chat](https://material.io/icons/#ic_chat)
- Phone icon as today

For print version, same info as available in digital, but printed as text instead of icons so they are visible. All icons in toolbar will be hidden when printed.

**Comment by DanielCaspers** [comment]
So, we didn't have an email in the store data endpoint, so I didn't include that one. But text and call are there, which are most important anyways. 

Here's what it will look like when you print. The store contact information is dynamic by company number, which is inferred from the work order ID's first 3 digits.

![image](https://user-images.githubusercontent.com/6056563/35188503-d7c029ba-fdfb-11e7-8023-cf4ac03ceb21.png)
