### ISSUE TITLE
Add HTML title & Favicon

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#86]
The page title is unassigned.  Please make it "Digital Inspection".
Favicon use "https://www.murphyauto.com/favicon.ico"
Also use the favicon on CA portal

**Comment by DanielCaspers** [comment]
The page title is only unassigned from the login screen AFAIK. I tried checking every page I could think of. If you find more occurences, please let me know.

**Comment by DanielCaspers** [comment]
CA2 has latest client build now. You'll have to copy to ca.murphyauto.net to get the favicon fix. 

Also AFAIK it seems the JSON serializer is breaking CA on your new field. I'll have to regression test that before closing #85
