### ISSUE TITLE
CA portal inspection report changes

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#92]
- [x] Vehicle odometer (layout near other vehicle info)
- [x] VIN (layout with other vehicle info)
- [x] Inspection Date (layout flexed to the right of order number. Consider mobile case.)

**Comment by DanielCaspers** [comment]
@scaspers assigned to you until you figure out which date to use under what circumstances based on our call today.

**Comment by scaspers** [comment]
I am thinking that the new [orderstatus endpoint](https://github.com/scaspers/D3-API/issues/20) will be the tool of choice or I can create a new field in the orders json object that uses the same code to derive.  The new endpoint could also be used by the app to set a status (ie. "Inspection Complete") when a tech is done with an inspection.  This can be used to notify the service advisor.

**Comment by scaspers** [comment]
@DanielCaspers  The inspection date can now be derived from the orders endpoint
 `"inspectionCompleted": 1524003140`.
This is a timestamp and we would like to display date only not time.  If the inspection was not marked completed then it will be null.

**Comment by scaspers** [comment]
For the Customer view.
Suggest that checklist items that are OK have some way of noting when there is additional info like measurements or a comment\canned response.

**Comment by DanielCaspers** [comment]
[CA-Portal_Customer_DI.zip](https://github.com/DanielCaspers/DigitalInspection/files/1959252/CA-Portal_Customer_DI.zip)

[CA-Portal_Customer_DI2.zip](https://github.com/DanielCaspers/DigitalInspection/files/1959248/CA-Portal_Customer_DI2.zip)

**Comment by DanielCaspers** [comment]
[CA-Portal_CustomerUxTweaks_DI2.zip](https://github.com/DanielCaspers/DigitalInspection/files/1959283/CA-Portal_CustomerUxTweaks_DI2.zip)
[CA-Portal_CustomerUxTweaks_DI.zip](https://github.com/DanielCaspers/DigitalInspection/files/1959284/CA-Portal_CustomerUxTweaks_DI.zip)
