### ISSUE TITLE
Notes Indicator

### ISSUE THREAD

**Issue by YoMurphy** [DanielCaspers/DigitalInspection#94]
Change icon or add indicator if there are any comments within any notes field.
![capture](https://user-images.githubusercontent.com/25590044/38627451-992d78d4-3d74-11e8-929c-d6c77aaea6a7.JPG)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy I took my first stab at it as an idea and merged it so you can pull it onto your server.

 I need to work on the "reactive" nature of the icon, but just to get an idea of switching icon assets, tell me what you think the icons I'm switching between. 
![apr-11-2018-9_08-pm](https://user-images.githubusercontent.com/6056563/38652701-bb7ca510-3dcc-11e8-8bad-c958d81dd7d9.gif)

Note that the page must be manually refreshed at the moment in order for this to work (or requires a user flow that refreshes the entire page on success).

**Also, for another bug fix I made in this evening, please request that all techs "empty cache and hard reload" on their tablets for DI.**

**Comment by YoMurphy** [comment]
This is great. Exactly what we were thinking. However @scaspers mentioned there was no changes to push to server.

**Comment by DanielCaspers** [comment]
I de-prioritized this in the milestone now from 1st to 5th
