### ISSUE TITLE
Vehicle options check boxes

### ISSUE THREAD

**Issue by YoMurphy** [DanielCaspers/DigitalInspection#95]
A few select popular vehicle options like ABS, A/C, AWD, 4WD can be selected within the vehcile tab. This is really is a means to make sure the tech provides these details to the adviser prior to estimating. 

I will inquire with the techs if there are other option items. The above are the only options currently on our work orders.

**Comment by DanielCaspers** [comment]
@scaspers what work order fields does this correspond to?

**Comment by DanielCaspers** [comment]
@scaspers let's prefer bools over ints as far as the Json is concerned. IDK if you have truthy/falsy checking in PHP, but that would be preferred from an API cleanliness standpoint.

Also, I find that usually using 'has' or 'is' as prefixes to boolean properties helps one infer types nicely even in environments where it isn't obvious, like JSON.

```

"vehicle": {
   "options": {
      "hasAC": false,
      "has4WD": true,
      "hasAWD": false,
      "hasABS": true
   }
},

```

Thoughts?

**Comment by scaspers** [comment]
I agree.  This is ready to activate when you are.  It breaks the work order page so I suppose you need to do a bit of magic in the app.

**Comment by DanielCaspers** [comment]
Awaiting bug fix from @scaspers for `HTTP Put` updating the vehicle options. Please pull and validate when you've fixed your side. If everything seems up to par, please close this issue then.

**Comment by DanielCaspers** [comment]
NOTE. DUE TO CSS CHANGES, REQUIRES EMPTY CACHE AND HARD RELOAD.

**Comment by scaspers** [comment]
Finally found the multiple problems.
1 - I had to deal with converting booleans to strings before sending them to PICK.
2 - It seems I cannot support multi-nested objects just yet.
This mean we need to change the mapping on your end to this:
![image](https://user-images.githubusercontent.com/12421599/38817363-d7601c50-415d-11e8-8019-62bfecae9b4d.png)

Sorry about that.  Had I done PUT tests I would have found this before you started.

**Comment by DanielCaspers** [comment]
@scaspers, I'd recommend you click on the review above after you've educated yourself on the code related to what we are suspecting may be a mapping bug. It should hopefully give you a better idea what's going on under the hood.
