### ISSUE TITLE
Error when saving WO changes

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#96]
If a work order is missing the city and we try to update the mileage it will error.  This error can be eliminated and reproduced by adding the city or deleting the city.  The address state and ZIP were also empty but did not cause an error.

![image](https://user-images.githubusercontent.com/12421599/38696516-06cd72f0-3e55-11e8-9737-094ccadb8f19.png)

**Comment by DanielCaspers** [comment]
@scaspers Tell me who did the detective work on this one? This was so well researched that I say they can have a beer on me 🍺 

This is also a problem with `Customer.Name` until you integrate my fix (and DB change)

If you're curious, check out the commit review. Whoops.
