### ISSUE TITLE
Measurements auto populate to minimum

### ISSUE THREAD

**Issue by YoMurphy** [DanielCaspers/DigitalInspection#98]
When measurement fields are opened it defaults to the minimum number. This requires the technician to delete the current data before entering any new data. 
Solution suggestions: 
1) Clear field upon first entry or just leave the field blank.
2) Create a Default field between Minimum and Maximum in setup. Which could also be left blank.

**Comment by DanielCaspers** [comment]
### Solution
@YoMurphy , I went with an idea similar to Solution 1 above.

The default value for this `InspectionMeasurement.Value` is now empty (`null`), and remains as such when empty until a user changes it. Once changed, it will keep that numeric value forever. 

### Example
1.  2 Measurements assigned to some checklist item
2. Tech opens dialog for that inspection item
3. Tech enters **only 1 measurement** and saves.
4. When they next open the dialog, the one with a value has it, and the one without is still empty. Much like how work order fields work.

@scaspers 
### DB migration steps
First pull latest code from Git.

Then In the `InspectionMeasurements` Table in MySQL, you'll need to make the `Value` column nullable, and make a default value of `NULL`

![image](https://user-images.githubusercontent.com/6056563/38715999-11a83814-3ea4-11e8-9f2c-ce3b9d6ac9ba.png)

I will not close the bug until @scaspers gives green light on integration progress.

**Comment by scaspers** [comment]
DB updated and latest code deployed.
